### ISSUE TITLE
Missing '#include "signal.h"' in Validator.cpp

### ISSUE THREAD

**Issue by ImJimmi** [Tracktion/pluginval#24]
Pulled the latest version on mac.
Attempted to build in Xcode 8.2.1 but stopped by "Use of undeclared identifer 'kill'" on line 774 of Validator.cpp.

A quick Google of the error suggests adding '#include "signal.h"'.
Doing so has fixed the issue and resulted in a successful build.

**Comment by drowaudio** [comment]
I'm not sure I want to support Xcode 8. Is there a specific reason you're trying to build with that?

**Comment by ImJimmi** [comment]
I like to always use most recent versions where I can... Is Xcode 8 known to have issues?

**Comment by drowaudio** [comment]
Xcode 11 is the most recent version.
I don't have Xcode 8 installed to test with and I don't think it's supplied on any of the cloud build servers I use. So it's difficult to set a precedent supporting old Xcode versions.

**Comment by abrykt** [comment]
I think it sound like a good idea to include signal.h since things from signal.h is used in Validator.cpp. If it happens to build without that include it is just because some other header includes it, but that other header might change so that the content of signal.h is suddenly unavailable.

**Comment by abrykt** [comment]
with AppleClang 11 and without including signal.h I get:

error: use of undeclared identifier 'kill'
    kill (getpid(), SIGKILL);

and:

 error: no member named 'siginterrupt' in the global namespace
        ::siginterrupt (signals[i], 1);

**Comment by drowaudio** [comment]
This is on develop
